// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StarLight.MigrationService.Migrations
{
    [DbContext(typeof(MarketDataContext))]
    [Migration("20241114000221_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Symbol");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Symbol = "AAPL",
                            Name = "Apple Inc."
                        },
                        new
                        {
                            Symbol = "MSFT",
                            Name = "Microsoft Corporation"
                        },
                        new
                        {
                            Symbol = "AMZN",
                            Name = "Amazon.com, Inc."
                        },
                        new
                        {
                            Symbol = "GOOGL",
                            Name = "Alphabet Inc."
                        },
                        new
                        {
                            Symbol = "META",
                            Name = "Meta Platforms, Inc."
                        },
                        new
                        {
                            Symbol = "BRK.B",
                            Name = "Berkshire Hathaway Inc."
                        },
                        new
                        {
                            Symbol = "JNJ",
                            Name = "Johnson & Johnson"
                        },
                        new
                        {
                            Symbol = "JPM",
                            Name = "JPMorgan Chase & Co."
                        },
                        new
                        {
                            Symbol = "V",
                            Name = "Visa Inc."
                        },
                        new
                        {
                            Symbol = "PG",
                            Name = "Procter & Gamble Co."
                        },
                        new
                        {
                            Symbol = "NVDA",
                            Name = "NVIDIA Corporation"
                        },
                        new
                        {
                            Symbol = "UNH",
                            Name = "UnitedHealth Group Incorporated"
                        },
                        new
                        {
                            Symbol = "HD",
                            Name = "Home Depot, Inc."
                        },
                        new
                        {
                            Symbol = "MA",
                            Name = "Mastercard Incorporated"
                        },
                        new
                        {
                            Symbol = "DIS",
                            Name = "Walt Disney Company"
                        },
                        new
                        {
                            Symbol = "PYPL",
                            Name = "PayPal Holdings, Inc."
                        },
                        new
                        {
                            Symbol = "INTC",
                            Name = "Intel Corporation"
                        },
                        new
                        {
                            Symbol = "VZ",
                            Name = "Verizon Communications Inc."
                        },
                        new
                        {
                            Symbol = "NFLX",
                            Name = "Netflix, Inc."
                        },
                        new
                        {
                            Symbol = "KO",
                            Name = "Coca-Cola Company"
                        },
                        new
                        {
                            Symbol = "PEP",
                            Name = "PepsiCo, Inc."
                        },
                        new
                        {
                            Symbol = "ADBE",
                            Name = "Adobe Inc."
                        },
                        new
                        {
                            Symbol = "CSCO",
                            Name = "Cisco Systems, Inc."
                        },
                        new
                        {
                            Symbol = "XOM",
                            Name = "Exxon Mobil Corporation"
                        },
                        new
                        {
                            Symbol = "NKE",
                            Name = "Nike, Inc."
                        },
                        new
                        {
                            Symbol = "PFE",
                            Name = "Pfizer Inc."
                        },
                        new
                        {
                            Symbol = "T",
                            Name = "AT&T Inc."
                        },
                        new
                        {
                            Symbol = "CVX",
                            Name = "Chevron Corporation"
                        },
                        new
                        {
                            Symbol = "ABBV",
                            Name = "AbbVie Inc."
                        },
                        new
                        {
                            Symbol = "CRM",
                            Name = "Salesforce.com, Inc."
                        },
                        new
                        {
                            Symbol = "WMT",
                            Name = "Walmart Inc."
                        },
                        new
                        {
                            Symbol = "CMCSA",
                            Name = "Comcast Corporation"
                        },
                        new
                        {
                            Symbol = "MCD",
                            Name = "McDonald's Corporation"
                        },
                        new
                        {
                            Symbol = "MDT",
                            Name = "Medtronic plc"
                        },
                        new
                        {
                            Symbol = "TMO",
                            Name = "Thermo Fisher Scientific Inc."
                        },
                        new
                        {
                            Symbol = "COST",
                            Name = "Costco Wholesale Corporation"
                        },
                        new
                        {
                            Symbol = "AMGN",
                            Name = "Amgen Inc."
                        },
                        new
                        {
                            Symbol = "AVGO",
                            Name = "Broadcom Inc."
                        },
                        new
                        {
                            Symbol = "BMY",
                            Name = "Bristol-Myers Squibb Company"
                        },
                        new
                        {
                            Symbol = "QCOM",
                            Name = "Qualcomm Incorporated"
                        },
                        new
                        {
                            Symbol = "TXN",
                            Name = "Texas Instruments Incorporated"
                        },
                        new
                        {
                            Symbol = "HON",
                            Name = "Honeywell International Inc."
                        },
                        new
                        {
                            Symbol = "UNP",
                            Name = "Union Pacific Corporation"
                        },
                        new
                        {
                            Symbol = "MMM",
                            Name = "3M Company"
                        },
                        new
                        {
                            Symbol = "SBUX",
                            Name = "Starbucks Corporation"
                        },
                        new
                        {
                            Symbol = "GS",
                            Name = "Goldman Sachs Group, Inc."
                        },
                        new
                        {
                            Symbol = "AXP",
                            Name = "American Express Company"
                        },
                        new
                        {
                            Symbol = "BA",
                            Name = "Boeing Company"
                        },
                        new
                        {
                            Symbol = "C",
                            Name = "Citigroup Inc."
                        },
                        new
                        {
                            Symbol = "GE",
                            Name = "General Electric Company"
                        },
                        new
                        {
                            Symbol = "LMT",
                            Name = "Lockheed Martin Corporation"
                        },
                        new
                        {
                            Symbol = "MS",
                            Name = "Morgan Stanley"
                        },
                        new
                        {
                            Symbol = "RTX",
                            Name = "Raytheon Technologies Corporation"
                        },
                        new
                        {
                            Symbol = "IBM",
                            Name = "International Business Machines Corporation"
                        },
                        new
                        {
                            Symbol = "TGT",
                            Name = "Target Corporation"
                        },
                        new
                        {
                            Symbol = "CVS",
                            Name = "CVS Health Corporation"
                        },
                        new
                        {
                            Symbol = "CAT",
                            Name = "Caterpillar Inc."
                        },
                        new
                        {
                            Symbol = "LLY",
                            Name = "Eli Lilly and Company"
                        },
                        new
                        {
                            Symbol = "ANTM",
                            Name = "Anthem, Inc."
                        },
                        new
                        {
                            Symbol = "UPS",
                            Name = "United Parcel Service, Inc."
                        },
                        new
                        {
                            Symbol = "NEE",
                            Name = "NextEra Energy, Inc."
                        },
                        new
                        {
                            Symbol = "PM",
                            Name = "Philip Morris International Inc."
                        },
                        new
                        {
                            Symbol = "SYK",
                            Name = "Stryker Corporation"
                        },
                        new
                        {
                            Symbol = "AMT",
                            Name = "American Tower Corporation"
                        },
                        new
                        {
                            Symbol = "CI",
                            Name = "Cigna Corporation"
                        },
                        new
                        {
                            Symbol = "GILD",
                            Name = "Gilead Sciences, Inc."
                        },
                        new
                        {
                            Symbol = "MDLZ",
                            Name = "Mondelez International, Inc."
                        },
                        new
                        {
                            Symbol = "INTU",
                            Name = "Intuit Inc."
                        },
                        new
                        {
                            Symbol = "BKNG",
                            Name = "Booking Holdings Inc."
                        },
                        new
                        {
                            Symbol = "NOW",
                            Name = "ServiceNow, Inc."
                        },
                        new
                        {
                            Symbol = "MU",
                            Name = "Micron Technology, Inc."
                        },
                        new
                        {
                            Symbol = "CHTR",
                            Name = "Charter Communications, Inc."
                        },
                        new
                        {
                            Symbol = "GM",
                            Name = "General Motors Company"
                        },
                        new
                        {
                            Symbol = "F",
                            Name = "Ford Motor Company"
                        },
                        new
                        {
                            Symbol = "COP",
                            Name = "ConocoPhillips"
                        },
                        new
                        {
                            Symbol = "DAL",
                            Name = "Delta Air Lines, Inc."
                        },
                        new
                        {
                            Symbol = "LUV",
                            Name = "Southwest Airlines Co."
                        },
                        new
                        {
                            Symbol = "AAL",
                            Name = "American Airlines Group Inc."
                        },
                        new
                        {
                            Symbol = "MAR",
                            Name = "Marriott International, Inc."
                        },
                        new
                        {
                            Symbol = "HLT",
                            Name = "Hilton Worldwide Holdings Inc."
                        },
                        new
                        {
                            Symbol = "DUK",
                            Name = "Duke Energy Corporation"
                        },
                        new
                        {
                            Symbol = "D",
                            Name = "Dominion Energy, Inc."
                        },
                        new
                        {
                            Symbol = "SO",
                            Name = "Southern Company"
                        },
                        new
                        {
                            Symbol = "EXC",
                            Name = "Exelon Corporation"
                        },
                        new
                        {
                            Symbol = "PEG",
                            Name = "Public Service Enterprise Group Incorporated"
                        },
                        new
                        {
                            Symbol = "PCG",
                            Name = "PG&E Corporation"
                        },
                        new
                        {
                            Symbol = "ED",
                            Name = "Consolidated Edison, Inc."
                        },
                        new
                        {
                            Symbol = "XEL",
                            Name = "Xcel Energy Inc."
                        },
                        new
                        {
                            Symbol = "SRE",
                            Name = "Sempra Energy"
                        },
                        new
                        {
                            Symbol = "ES",
                            Name = "Eversource Energy"
                        },
                        new
                        {
                            Symbol = "FE",
                            Name = "FirstEnergy Corp."
                        },
                        new
                        {
                            Symbol = "ETR",
                            Name = "Entergy Corporation"
                        },
                        new
                        {
                            Symbol = "PPL",
                            Name = "PPL Corporation"
                        },
                        new
                        {
                            Symbol = "AEE",
                            Name = "Ameren Corporation"
                        },
                        new
                        {
                            Symbol = "CNP",
                            Name = "CenterPoint Energy, Inc."
                        },
                        new
                        {
                            Symbol = "NI",
                            Name = "NiSource Inc."
                        },
                        new
                        {
                            Symbol = "LNT",
                            Name = "Alliant Energy Corporation"
                        },
                        new
                        {
                            Symbol = "AGR",
                            Name = "Avangrid, Inc."
                        },
                        new
                        {
                            Symbol = "CMS",
                            Name = "CMS Energy Corporation"
                        },
                        new
                        {
                            Symbol = "DTE",
                            Name = "DTE Energy Company"
                        });
                });

            modelBuilder.Entity("HistoricalPrice", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Symbol", "DateTime");

                    b.ToTable("HistoricalPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
